mongodb/docs-landing

src/sass/bem-components/main.scss

Related PR on `mongodb/docs-tools`: [https://github.com/mongodb/docs-tools/pull/155](https://github.com/mongodb/docs-tools/pull/155)

DOCSP-998: Prevent sidebar overlapping main content.

---

src/sass/bem-components/card.scss

Stage: https://docs-mongodbcom-staging.corp.mongodb.com/landing/nick/DOCSP-1002/index.html
The reference image on the ticket didn't have great resolution or specifics on box shadow implementation so take a look and see if it seems to have the right shade and distance. Transition speed matches the landing page accordions exactly, as specified in the ticket.

DOCSP-1002: Hover state on cards

---

src/html/home.html

@i80and : Can you check and see if I broke anything? It looks right. I [staged the change on the main landing page](https://docs-mongodbcom-staging.corp.mongodb.com/landing/anthonysansone/DOCSP-4828/).
@jdestefano-mongo : I am unsure if this should also go on the Tools or Cloud pages. Both are nice even 2x2 grids, etc. Maybe we can stay with just the one landing for now?

(DOCSP-4828): Update with k8s Operator.

---

snooty.toml
source/legacy.txt

[[JIRA](https://jira.mongodb.org/browse/DOP-909)] [[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/DOP-909/legacy)] Add page at https://docs.mongodb.com/legacy to link to deprecated documentation. At the moment, nothing in Docs links to this page, so it will effectively be in stealth mode until some documentation is deprecated.
@jdestefano-mongo I added you as a reviewer in order to verify that we've included the correct versions for each product in the dropdown. I used [this spreadsheet](https://docs.google.com/spreadsheets/d/1AVS8NdMecph_xfmr44lI_zwHoowQfpgG6AJkSlx9e2w/edit#gid=794571501) as a reference and omitted the docs not hosted on docs.mongodb.com (drivers). Appreciate your help in advance—let me know if I can clarify anything!

DOP-909: Add legacy page

---

source/search.txt

[JIRA](https://jira.mongodb.org/browse/DOP-1337)
[Spec](https://docs.google.com/document/d/10TAxNOdWDp_vi-D_NTnA_YDQXLeyoPsFa2Banx1Srsw/edit#heading=h.pyglchaeju4o)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/DOP-1337/search)
[Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f36e7cc2f9a5cfb5b242c80)
This PR adds a new page at `/search` which simply invokes the new `search-results` directive to prepare for the new search UI.
This should not be merged until we are ready for the new Searchbar. Specifically we will also have to merge/deploy:
- [docs-tools #448](https://github.com/mongodb/docs-tools/pull/448)
- A forthcoming Snooty front-end branch `search-ui`

DOP-1337 Add search page with search-results directive

---

src/html/_layout.html

Update the GTM ID to the new ID: `https://www.googletagmanager.com/ns.html?id=GTM-GDFN`.
[docs-landing](https://docs-mongodborg-staging.corp.mongodb.com/DOP-GTM/landing/cgoecknerwald/master/).

Update GTM ID

---

gen_landings.py
src/html/_layout.html

Adds a `rel=canonical` link to docs.mongodb.com/tools/ and docs.mongodb.com/cloud/ in support of the SEO efforts.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/landing/allison/master/tools/index.html

DOP-1882: add canonical link to landing pages

---

static/sitemap-index.xml

Atlas OSB is deprecated so we don't want Google to find it, I think!

Remove Atlas OSB from sitemap index

---

snooty.toml

[DOP-2215](https://jira.mongodb.org/browse/DOP-2215).
[snooty-parser](https://github.com/mongodb/snooty-parser/pull/314).

DOP-2215: Remove default_domain

---

snooty.toml

[JIRA](https://jira.mongodb.org/browse/DOCSP-20845)
[Clean build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=629a5aaa7cf5397525b634a9)
This PR adds the Atlas Open Service Broker to the Legacy Docs product menu.
To be completed with https://github.com/10gen/cloud-docs-osb/pull/27

(DOCSP-20845):  Deprecate AOSB and move to Legacy Docs site

---

source/index.txt

Staging: https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/shell-fix/

Remove legacy mongo shell reference from the landing page.

---

source/openapi/preview.txt

[DOP-3427](https://jira.mongodb.org/browse/DOP-3427)
[OpenAPI preview page](https://www.mongodb.com/docs/openapi/preview/) - should be built with client-side rendering
[OpenAPI preview page](https://docs-mongodb-org-dotcomstg.s3.us-east-2.amazonaws.com/landing/docsworker-xlarge/DOP-3427-origin/openapi/preview/index.html) - should be built with client-side rendering; built using Autobuilder's pre-prd staging webhook
* Adds `preview` option to `openapi` directive. This will flag to the parser to not build OpenAPI metadata for this page to allow the frontend to render this page client-side (as opposed to statically).
* Tested this option locally using the Autobuilder's OpenAPI Page Builder module and using the Autobuilder's pre-prd staging webhook ([build …

DOP-3427: Add preview option to openapi preview page

---

config/redirects

[DOP-3455](https://jira.mongodb.org/browse/DOP-3455)
* No content change, so no staging link for now.
* Will perform a `/deploy` after merging and check to ensure that the following URLs are redirected properly:
* https://mongodb.com/docs/tools -> https://mongodb.com/docs/view-analyze/
* https://mongodb.com/docs/cloud -> https://mongodb.com/docs/launch-manage/

DOP-3455: Update base url for redirects

---

source/index.txt

Add Kotlin to list of drivers on landing page
To be merged and deployed next Wed (June 21) in preparation for NYC.local, if possible.
[Jira](https://jira.mongodb.org/browse/DOCSP-30244)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/docsp-30244/)

(DOCSP-30244): Add Kotlin to landing page card

---

snooty.toml

[DOCSP-30859](https://jira.mongodb.org/browse/DOCSP-30859)
adding EOL versions of kafka connector to snooty.toml

DOCSP-30859-eol-kafka-v1.0-v1.7

---

snooty.toml

[DOCSP-30858](https://jira.mongodb.org/browse/DOCSP-30858)
Added VScode extension/analyzer v1.0 to deprecated versions

DOCSP-30858: eol-analyzer-v1.0

---

source/index.txt

https://preview-mongodbrustagir.gatsbyjs.io/landing/DOCSP-33640-rust-new-docs/
the rust link 404s, but the link should be correct

DOCSP-33640: link to new rust docs

---

source/develop-applications.txt

Realm has been rebranded to Atlas Device SDK. We updated other parts of the docs, but this page slipped through the cracks. Related to the work in this Jira ticket: https://jira.mongodb.org/browse/DOCSP-37609

Rename "Realm" to "Atlas Device SDK"

---

source/tools-and-connectors.txt

[Staging](https://preview-mongodbmelissamahoneymongodb.gatsbyjs.io/landing/DOCSP-37691/tools-and-connectors/)
This PR:
* Removes individual products from the left nav on the Migrators, Tools, and Connectors landing page
* Creates TOC entries that point to the section headings on the page
* Moves the Gen AI FAQs to the bottom of the page
[Clean build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f1f8eb6fc5f0485031648c)

(DOCSP-37691) Adjust Migrators, Tools & Connectors TOC to point to section headings

---

source/index.txt

This rST change is an attempt to have the bottom cards use a general style option that should be reusable for the programming language landing pages.
**This PR should be merged AFTER releasing the [frontend](https://github.com/mongodb/snooty/pull/1062) and [parser](https://github.com/mongodb/snooty-parser/pull/584) PRs.**
[Staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4543-generalize-cards/landing/raymund.rodriguez/main/index.html#more-ways-to-learn)
[Prod link](https://www.mongodb.com/docs/#more-ways-to-learn)
[Related PR comment](https://github.com/mongodb/snooty/pull/1062#issuecomment-2052432691).

DOP-4543: Generalize bottom cards to use large-icon style

---

source/languages/php.txt
source/launch-manage.txt

Removed Yii framework from PHP landing page. 
- [DOCSP-44171](https://jira.mongodb.org/browse/DOCSP-44171)
- [STAGING](https://deploy-preview-214--docs-landing-mongodb.netlify.app/languages/php/)

(DOCSP-44171) [Docs-Landing] Removed Yii framework from PHP landing page.

---

source/tools-and-connectors.txt

Changes from #220, which adds IntelliJ to the Migrators, Tools, and Connectors docs home page.
https://deploy-preview-222--docs-landing-mongodb.netlify.app/tools-and-connectors/#ide-integrations
https://jira.mongodb.org/browse/DOCSP-45635

DOCSP-45635-intellij-docs-landing
