mongodb/docs-landing

- src/html/home.html
@kay-kim @i80and please make sure these changes are merged before we publish the redesign.
> Removed one sentence of gibberish and tweaked Hosting title.

- src/html/home.html
> Update landing page for 3.6 and switch Manual and Tutorials card.

- src/html/home.html
- src/html/tools.html
Staging:
- [Main TOC](https://docs-mongodbcom-staging.corp.mongodb.com/landing/melissamahoney/DOCSP-9372/index.html)
- [Tools landing page](https://docs-mongodbcom-staging.corp.mongodb.com/landing/melissamahoney/DOCSP-9372/tools/index.html)
> (DOCSP-9372): Update TOC & landing page for MongoDB Command Line Interface

- src/html/cloud.html
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/landing/jeffreyallen/DOCSP-9744/cloud/index.html)
> (DOCSP-9744): Add Charts to Cloud Landing page

- src/html/cloud.html
- src/html/home.html
[Jira](https://jira.mongodb.org/browse/DOCSP-10294)
Staged:
[Welcome to the MongoDB Docs](https://docs-mongodbcom-staging.corp.mongodb.com/landing/stevenrenaker/DOCSP-10294/)
[Cloud Products](https://docs-mongodbcom-staging.corp.mongodb.com/landing/stevenrenaker/DOCSP-10294/cloud/index.html)
> DOCSP-10294: [Atlas Search] add links to top-level Documentation TOCs

- src/html/tools.html
Adding our new products / repositories to the Tools Landing page
Staged: [Tools Landing](https://docs-mongodborg-staging.corp.mongodb.com/landing/jeffreyallen/DOCSP-10673/tools/index.html
)
> (DOCSP-10673): Add vsce and mongosh to Tools Landing

- src/html/_layout.html
Update second instance of GTM ID
> DOP-GTM: Update GTM ID

- src/html/_layout.html
[[`/cloud` Staging](https://docs-mongodbcom-staging.corp.mongodb.com/landing/sophstad/master/cloud/index.html)] [[`/tools` Staging](https://docs-mongodbcom-staging.corp.mongodb.com/landing/sophstad/master/tools/index.html)] Standardize behavior with the rest of docs properties.
> Add tracking event

- source/index.txt
[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1197)]
[[Landing staging](https://docs-mongodbcom-staging.corp.mongodb.com/23a9054/landing/docsworker-xlarge/DOP-1197/)]
> DOP-1197: Swap Server and Atlas on home page

- source/index.txt
[docs-landing](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/cgoecknerwald/master/).
> add-alt: Add alt text to homepage hero

- src/html/cloud.html
- src/html/tools.html
Staging: https://docs-mongodborg-staging.corp.mongodb.com/b2e6634/landing/docsworker-xlarge/DOP-1883/
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6090560309293ae6260777d3
> DOP-1883: fix redirect chains, remove Atlas OSB

- source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOP-2117). 
Corresponding [snooty-parser change](https://github.com/mongodb/snooty-parser/pull/311).
> DOP-2117: Specify carousel Card layout

- source/index.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/2a2d8ea/landing/docsworker-xlarge/DOCSP-15452/
> DOCSP-15452: update landing page with new copy

- source/develop-applications.txt
- source/view-analyze.txt
[Docs Landing Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/grace.chong/DOP-2469/)
> DOP-2469: Move Kafka docs out of View and Analyze Data

- source/develop-applications.txt
- source/index.txt
- Name change.
- Added a separate "Realm SDKs" sidebar entry. No card, since then we'd end up with a row with only one card in it and it would look a bit wonky.
> Update "Realm" to "App Services" in cards & toc

- source/develop-applications.txt
- source/index.txt
https://jira.mongodb.org/browse/DOCSP-25898
- [/docs](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/baas-card/)
- [/docs/develop-applications](https://docs-mongodbcom-staging.corp.mongodb.com/landing/docsworker-xlarge/baas-card/develop-applications/)
> (DOCSP-25898) Update Copy on Atlas App Services PLP Cards

- source/index.txt
- source/search.txt
- source/tools-and-connectors.txt
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642b1a1db49106a498138590
Staging: https://docs-mongodborg-staging.corp.mongodb.com/landing/docsworker-xlarge/DOP-3546/
> DOP-3546: near-term modification of homepage & nav

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36132
> [C++] Update C++ Docs URL slug from cxx to cpp

- source/develop-applications.txt
Adds a meta description to the Develop Applications page. The landing page (index) already had a meta description.
[Jira](https://jira.mongodb.org/browse/DOCSP-38257)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66167b793a5920a291ccb413)
[Staging](https://preview-mongodbsarahsimpers.gatsbyjs.io/landing/DOCSP-38257/develop-applications/)
> (DOCSP-38257) Adds meta desc to Develop Applications page

- source/tools-and-connectors.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-38454)
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/landing/DOCSP-38454/tools-and-connectors/#management-tools)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661952093a5920a29192a10e)
> adds tools-and-connectors tile for AKO

- source/languages/python.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39190
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/landing/DOCSP-39190-fix-python-link/languages/python/
> DOCSP-39190: Fix PyMongo link

- source/languages/php.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39189
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/landing/DOCSP-39189-symfony-link/languages/php/
> DOCSP-39189: Update Symfony link

- source/languages/javascript.txt
https://jira.mongodb.org/browse/DOCSP-39215
[Staging](https://preview-mongodbrustagir.gatsbyjs.io/landing/DOCSP-39215-update-node-link/languages/javascript/)
> DOCSP-39215: update node link

- source/languages/php.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-39904)
[Staging](https://preview-mongodbjordansmith721.gatsbyjs.io/landing/DOCSP-39904-flysystem-integration/languages/php/#integrations)
> DOCSP-39904 Add Flysystem to PHP integrations list

- source/languages/python.txt
[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)
JIRA - <https://jira.mongodb.org/browse/DOCSP-40341>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/landing/DOCSP-40341-update-python-links/languages/python/>
> DOCSP-40341 update link

- source/languages/php.txt
[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)
JIRA - <https://jira.mongodb.org/browse/DOCSP-40342>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/landing/DOCSP-40342-update-php-landing-copy/languages/php/>
> DOCSP-40342 update php copy

- source/languages/php.txt
https://jira.mongodb.org/browse/DOCSP-39180
Links to the new integration pg from PHP landing page
[STAGING](https://preview-mongodbrustagir.gatsbyjs.io/landing/DOCSP-39180-php-symfony-link/languages/php/)
> DOCSP-39180: link to new symfony guide

- source/languages/csharp.txt
Updating C# Driver description and adding a description for the EF provider
[Jira](https://jira.mongodb.org/browse/DOCSP-39419)
[Staging](https://preview-mongodbjordansmith721.gatsbyjs.io/landing/DOCSP-39419-Csharp-ef-summaries/languages/csharp/)
> DOCSP-39419 Update C# Driver and EF descriptions

- source/languages/java.txt
https://jira.mongodb.org/browse/DOCSP-40219
staging: https://preview-mongodbrustagir.gatsbyjs.io/landing/DOCSP-39554-spring-ai-link/languages/java/
> DOCSP-40219: add spring ai link to java landing page

- source/tools-and-connectors.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-42015)
[Staging](https://preview-mongodbkyuanmongodb.gatsbyjs.io/landing/DOCSP-42015/tools-and-connectors/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66aa9f7b824f175afd83cd9e)
> DOCSP-42015 orient express title name updates

- config/redirects
Added three new redirects as requested in the linked JIRA ticket.
[JIRA](https://jira.mongodb.org/browse/DOCSP-42119)
[Staging](https://preview-mongodbkyuanmongodb.gatsbyjs.io/landing/DOCSP-42119/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66b233d5824f175afd145f9d)
> DOCSP-42119 added new redirects

- source/languages/javascript.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42399
Staging - https://deploy-preview-203--docs-landing-mongodb.netlify.app/languages/javascript/
> DOCSP-42399: Add Flowise link to Node landing page

- source/generative-ai-faq.txt
Adds VSCode's AI and Data Usage page to the GenAI FAQ
https://deploy-preview-213--docs-landing-mongodb.netlify.app/generative-ai-faq/#what-data-is-sent-to-the-model-
https://jira.mongodb.org/browse/DOCSP-44028
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)
> DOCSP-44028-adding-vscode-to-genai-faq

- source/languages/csharp.txt
Adding two integrations to the C# landing page
Jira - https://jira.mongodb.org/browse/DOCSP-40741
Staging - https://deploy-preview-215--docs-landing-mongodb.netlify.app/languages/csharp/
> DOCSP-40741 Add integrations to C# landing page

- source/languages/csharp.txt
Update the link for Semantic Kernal on C# landing page
Jira - https://jira.mongodb.org/browse/DOCSP-40741
Staging - https://deploy-preview-216--docs-landing-mongodb.netlify.app/languages/csharp/
> C# - Change Semantic Kernal link

- source/languages/php.txt
> DOCSP-44610: fix php links

- source/languages/csharp.txt
Fixing typo on C# landing page
[Jira](https://jira.mongodb.org/browse/DOCSP-45224)
[Staging](https://deploy-preview-218--docs-landing-mongodb.netlify.app/languages/csharp/#frameworks-and-integrations)
> DOCSP-45334 C# landing typo fix

- source/tools-and-connectors.txt
Reverts mongodb/docs-landing#220
> Revert "DOCSP-45635-add-intellij-docs"

- source/languages/c.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45657
Staging - https://deploy-preview-223--docs-landing-mongodb.netlify.app/languages/c/
> DOCSP-45657: Fix libbson and libmongoc links

- source/legacy.txt
Adds clarity to the legacy documentation page
https://deploy-preview-224--docs-landing-mongodb.netlify.app/legacy/
https://jira.mongodb.org/browse/DOCSP-44217
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)
> DOCSP-44217 legacy documentation description

- source/languages/java.txt
- source/languages/javascript.txt
- source/languages/php.txt
- source/languages/python.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39452
Staging - https://deploy-preview-228--docs-landing-mongodb.netlify.app/languages/java/
https://deploy-preview-228--docs-landing-mongodb.netlify.app/languages/javascript/
https://deploy-preview-228--docs-landing-mongodb.netlify.app/languages/php/
https://deploy-preview-228--docs-landing-mongodb.netlify.app/languages/python/
> DOCSP-39452: Developer exams

- source/index.txt
Edit the following two sentences on the [landing page](https://www.mongodb.com/docs/): 
1. Hero banner/image thing:
**From:** "...needed to build applications on MongoDB and the Atlas developer data platform."
**To:** "... needed to build applications on the world’s most popular modern database."
2. Atlas card below the hero:
**From:** "Run MongoDB on a multi-cloud developer data platform that accelerates and simplifies working with operational data."
**To:** "The modern multi-cloud database that accelerates and simplifies how you build with data."
[DOCSP-48510](https://jira.mongodb.org/browse/DOCSP-48510)
https://deploy-preview-229--docs-landing-mongodb.netlify.app/
> (DOCSP-48510) [Landing] Update DDP Messaging.

- source/languages/cpp.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48630
Staging - https://deploy-preview-230--docs-landing-mongodb.netlify.app/languages/cpp/
> DOCSP-48630: Update C++ get started link

- source/languages/go.txt
- [DOCSP-44538](https://jira.mongodb.org/browse/DOCSP-44538)
- [Staging](https://deploy-preview-234--docs-landing-mongodb.netlify.app/languages/go/)
> DOCSP-44538 Add LangChainGo tutorial link

- source/index.txt
staging: https://deploy-preview-239--docs-landing-mongodb.netlify.app/
https://jira.mongodb.org/browse/DOCSP-49730
> DOCSP-49370: Homepage

- source/preview-features.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50380
Staging - https://deploy-preview-244--docs-landing-mongodb.netlify.app/preview-features/
> DOCSP-50380: Preview features page
